"""
Har snapshot ka ek printable HTML report banata hai — District Magistrate /
SDMA officer ke record ke liye. Browser ka "Print to PDF" isse PDF bana deta hai.
"""

from datetime import datetime, timezone


def build_report_html(df, lang: str = "en") -> str:
    now = datetime.now(timezone.utc).strftime("%d %B %Y, %H:%M UTC")
    title = "आपदा जोखिम प्राथमिकता रिपोर्ट" if lang == "hi" else "Disaster Risk Priority Report"
    subtitle = "रुद्रप्रयाग जिला — भूस्खलन जोखिम मूल्यांकन" if lang == "hi" else "Rudraprayag District — Landslide Risk Assessment"

    rows = ""
    for _, r in df.iterrows():
        site = r["recommended_site"] or "—"
        rows += f"""
        <tr>
          <td>{r['priority_rank']}</td>
          <td>{r['village_name']} ({r['tehsil']})</td>
          <td>{r['hazard_score']}</td>
          <td class="tier-{r['tier'].lower()}">{r['tier']}</td>
          <td>{site}</td>
          <td>{r['population']}</td>
        </tr>"""

    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>{title}</title>
<style>
  body {{ font-family: Arial, sans-serif; padding: 30px; color: #1f2937; }}
  h1 {{ color: #7c2d12; margin-bottom: 2px; }}
  .subtitle {{ color: #6b7280; margin-bottom: 4px; }}
  .meta {{ font-size: 12px; color: #9ca3af; margin-bottom: 20px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th {{ background: #7c2d12; color: white; padding: 8px; text-align: left; }}
  td {{ border: 1px solid #e5e7eb; padding: 8px; }}
  tr:nth-child(even) {{ background: #fafaf9; }}
  .tier-critical {{ color: #dc2626; font-weight: bold; }}
  .tier-red {{ color: #ea580c; font-weight: bold; }}
  .tier-watch {{ color: #d97706; font-weight: bold; }}
  .tier-safe {{ color: #16a34a; font-weight: bold; }}
  .footer {{ margin-top: 24px; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 10px; }}
  @media print {{ button {{ display: none; }} }}
</style></head>
<body>
  <button onclick="window.print()" style="padding:8px 16px;background:#b45309;color:white;border:none;border-radius:6px;cursor:pointer;margin-bottom:16px;">
    🖨️ Print / Save as PDF
  </button>
  <h1>{title}</h1>
  <div class="subtitle">{subtitle}</div>
  <div class="meta">Generated: {now} · SIH26191 Hazard Red Zone Platform</div>
  <table>
    <tr><th>#</th><th>Habitation</th><th>Score</th><th>Tier</th><th>Recommended Site</th><th>Population</th></tr>
    {rows}
  </table>
  <div class="footer">
    Data sources: NRSC Landslide Atlas of India (2023), NASA SRTM elevation data (via OpenTopography).
    Generated by SIH26191 Hazard Red Zone &amp; Relocation Priority Platform — a decision-support tool;
    final relocation decisions should be validated by the State Disaster Management Authority.
  </div>
</body></html>"""